kookmin-sw/capstone-2023-09

src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.tsx, src/front-end/timepay-front/yarn.lock
=> 머지 실수 최종 수정..

src/front-end/timepay-admin/src/components/PostSearchForm/PostSearchForm.styles.tsx, src/front-end/timepay-admin/src/components/PostSearchForm/PostSearchForm.tsx, src/front-end/timepay-admin/src/components/PostTable/PostTable.tsx
- 게시글 검색값 축소
- 테이블에 작성자 닉네임 추가 및 순서 일부 변경
=> [관리자] 게시글 검색값 축소 및 테이블 컬럼 추가

src/front-end/timepay-admin/src/App.tsx, src/front-end/timepay-admin/src/api/interfaces/IComment.ts, src/front-end/timepay-admin/src/components/CommentHideModal/CommentHideModal.styles.ts, src/front-end/timepay-admin/src/components/CommentHideModal/CommentHideModal.tsx, src/front-end/timepay-admin/src/components/CommentHideModal/index.ts, src/front-end/timepay-admin/src/components/CommentSearchForm/CommentSearchForm.styles.tsx, src/front-end/timepay-admin/src/components/CommentSearchForm/CommentSearchForm.tsx, src/front-end/timepay-admin/src/components/CommentSearchForm/index.ts, src/front-end/timepay-admin/src/components/CommentTable/CommentTable.styles.tsx, src/front-end/timepay-admin/src/components/CommentTable/CommentTable.tsx, src/front-end/timepay-admin/src/components/CommentTable/index.ts, src/front-end/timepay-admin/src/components/PostSearchForm/PostSearchForm.styles.tsx, src/front-end/timepay-admin/src/pages/CommentManagement/CommentManagementPage.styles.tsx, src/front-end/timepay-admin/src/pages/CommentManagement/CommentManagementPage.tsx, src/front-end/timepay-admin/src/pages/CommentManagement/index.ts, src/front-end/timepay-admin/src/pages/index.ts, src/front-end/timepay-admin/src/styles/constants/colors.ts
댓글 관리 화면 검색, 테이블, 숨김 모달 UI 추가함
=> [관리자] 댓글 관리 페이지 UI 추가

src/front-end/timepay-front/src/App.tsx, src/front-end/timepay-front/src/api/interfaces/IComment.ts, src/front-end/timepay-front/src/components/ActivityCommentCard/ActivityCommentCard.styles.tsx, src/front-end/timepay-front/src/components/ActivityCommentCard/ActivityCommentCard.tsx, src/front-end/timepay-front/src/components/ActivityCommentCard/index.ts, src/front-end/timepay-front/src/components/ActivityPostCard/ActivityPostCard.styles.tsx, src/front-end/timepay-front/src/components/ActivityPostCard/ActivityPostCard.tsx, src/front-end/timepay-front/src/components/ActivityPostCard/index.ts, src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.styles.tsx, src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.tsx, src/front-end/timepay-front/src/pages/ActivityRecordPage/index.ts, src/front-end/timepay-front/src/pages/index.ts, src/front-end/timepay-front/src/utils/paths.ts
- 활동기록 화면용 게시글, 댓글 컴포넌트 추가(이후 타 유저 프로필 화면에도 사용 예정)
- 클릭 시 게시글 조회 화면으로 넘어가는 거나 필터 적용은 구현 예정
- 게시글 컴포넌트는 피그마 디자인에서 일부 수정함
=> [사용자] 활동 기록 화면 UI 개발

src/front-end/timepay-front/src/components/AnotherUserProfileDrawer/AnotherUserProfileDrawer.styles.tsx, src/front-end/timepay-front/src/components/AnotherUserProfileDrawer/AnotherUserProfileDrawer.tsx, src/front-end/timepay-front/src/components/AnotherUserProfileDrawer/index.ts, src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.styles.tsx, src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.tsx, src/front-end/timepay-front/src/styles/constants/tabStyle.ts
- 타유저 프로필 조회 화면 개발
- 활동 기록 화면에서 쓴 tabStyle 과 게시글, 댓글 컴포넌트 재사용 + 홈화면 상태, 유형 태그 컴포넌트 재활용함
- tabStyle 배경색 때문에 baseLayout 에서 height : 100vh 속성 추가함
=> [사용자] 타 유저 프로필 조회 화면 UI 개발

src/front-end/timepay-admin/src/api/interfaces/IQna.ts, src/front-end/timepay-admin/src/components/QnADetailModal/QnADetailModal.styles.ts, src/front-end/timepay-admin/src/components/QnADetailModal/QnADetailModal.tsx, src/front-end/timepay-admin/src/components/QnADetailModal/index.ts, src/front-end/timepay-admin/src/components/QnASearchForm/QnASearchForm.styles.tsx, src/front-end/timepay-admin/src/components/QnASearchForm/QnASearchForm.tsx, src/front-end/timepay-admin/src/components/QnASearchForm/index.ts, src/front-end/timepay-admin/src/components/QnATable/QnATable.styles.tsx, src/front-end/timepay-admin/src/components/QnATable/QnATable.tsx, src/front-end/timepay-admin/src/components/QnATable/index.ts, src/front-end/timepay-admin/src/pages/PasswordEdit/PasswordEditPage.tsx, src/front-end/timepay-admin/src/pages/QnAManagement/QnAManagementPage.styles.tsx, src/front-end/timepay-admin/src/pages/QnAManagement/QnAManagementPage.tsx, src/front-end/timepay-admin/yarn.lock
문의 관리 테이블 추가
문의 조회및 답변 작성 모달 추가
=> [관리자]문의 관리 화면 UI 추가

src/front-end/timepay-front/src/pages/FinishJoinPage/FinishJoinPage.tsx, src/front-end/timepay-front/yarn.lock
=> styled-component -> emotion/react

src/front-end/timepay-admin/src/api/hooks/notification.ts, src/front-end/timepay-admin/src/api/interfaces/ICommon.ts, src/front-end/timepay-admin/src/api/interfaces/INotification.ts, src/front-end/timepay-admin/src/api/urls.ts, src/front-end/timepay-admin/src/components/PushAddModal/PushAddModal.style.tsx, src/front-end/timepay-admin/src/components/PushAddModal/PushAddModal.tsx, src/front-end/timepay-admin/src/components/PushDeleteModal/PushDeleteModal.tsx, src/front-end/timepay-admin/src/components/PushDetailModal/PushDetailModal.tsx, src/front-end/timepay-admin/src/components/PushSearchForm/PushSearchForm.tsx, src/front-end/timepay-admin/src/components/PushTable/PushTable.tsx, src/front-end/timepay-admin/src/pages/PushManagement/PushManagementPage.tsx, src/front-end/timepay-admin/src/states/pushSearchState.ts
- 푸시(공지사항) 조회, 등록, 삭제 기능 연결
- 페이지네이션은 추후에 구현하겠습니다!
=> [관리자] 푸시 관리 메뉴 기능 연결

src/front-end/timepay-admin/package.json, src/front-end/timepay-admin/src/api/request.ts, src/front-end/timepay-front/package.json, src/front-end/timepay-front/src/api/request.ts
=> 프록시 주소를 aws 서버로 api url 수정

src/front-end/timepay-admin/src/api/hooks/notification.ts, src/front-end/timepay-admin/src/api/interfaces/INotification.ts, src/front-end/timepay-admin/src/components/PushDeleteModal/PushDeleteModal.tsx, src/front-end/timepay-admin/src/components/PushTable/PushTable.tsx
- 푸시 조회 시 admin 객체로 주던 부분이 adminId, adminName으로 변경됨
- 푸시 등록 시 request payload notice -> isNotice 로 변경
=> 공지 조회, 등록 api 변경으로 인한 변경

src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/dto/AdminDealBoardDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java
우선 회원가입시 무조건 회원가입 승인 상태로 변경
Convert String to Long 부분에서 발생한 오류 수정
=> User 관련 수정

src/front-end/timepay-admin/src/api/request.ts, src/front-end/timepay-front/package.json, src/front-end/timepay-front/src/api/hooks/user.ts, src/front-end/timepay-front/src/api/interfaces/IUser.ts, src/front-end/timepay-front/src/api/request.ts, src/front-end/timepay-front/src/api/urls.ts, src/front-end/timepay-front/src/pages/MyEditPage/MyEditPage.tsx, src/front-end/timepay-front/src/pages/MyPage/My.css, src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx
1. 요청에 따른 사용자 마이페이지 화면 디자인 일부 수정(버튼 배경색, border 등)
2. 사용자 마이페이지 화면 API 개발 완료
*사용자 지역, 소개 추가 예정
*유저 id 저장 필요
=> [사용자] 마이페이지 API 연결 완료

src/front-end/timepay-admin/src/api/hooks/comment.ts, src/front-end/timepay-admin/src/components/CommentTable/CommentTable.tsx, src/front-end/timepay-admin/src/components/PushTable/PushTable.tsx, src/front-end/timepay-admin/src/states/commentSearchState.ts, src/front-end/timepay-admin/src/states/pushSearchState.ts, src/front-end/timepay-admin/src/utils/pagination.ts
- 페이지네이션을 적용하기 쉽도록 공통 함수 추가함 
(공통 함수 수정할 필요가 있을 땐 꼭 말해주세요! 이 함수 사용하는 다른 화면에도 영향이 갑니당)
- 예시로 푸시 테이블과 댓글 테이블에 연결해뒀습니다~!
- 페이지 번호나 사이즈를 기억하도록 해놨어요!
사진은 페이지네이션해서 호출해본 결과입니다!  
페이지를 왔다갔다 할 때마다 알아서 api 호출해요!
=> [관리자] 페이지네이션 기능 추가

src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx
- API 주소 잘못되었고, 해당 API 구현 미완료로 인해 더미 데이터로 수정했습니다.
=> GET API 적용 철회, 더미 데이터 적용으로 수정

src/front-end/timepay-front/src/api/hooks/push.ts, src/front-end/timepay-front/src/api/interfaces/ICommon.ts, src/front-end/timepay-front/src/api/interfaces/IPush.ts, src/front-end/timepay-front/src/api/urls.ts, src/front-end/timepay-front/src/components/PushCollapse/PushCollapse.styles.tsx, src/front-end/timepay-front/src/components/PushCollapse/PushCollapse.tsx, src/front-end/timepay-front/src/pages/PushNotificationPage/PushNotificationPage.tsx, src/front-end/timepay-front/src/styles/constants/colors.ts, src/front-end/timepay-front/src/styles/constants/tabStyle.ts
- 전체 알림 화면에 공지사항 조회 api 연결함 -> 기존 Push 타입과 Notification 타입을 일단 같이 쓰게 함
- 탭 디자인 수정
- 추후 사용자별 알림 조회 api 개발되면 api url, api Response 타입 등 수정할 예정
=> [사용자] 전체 알림 화면에 공지사항 조회 api 연결

src/front-end/timepay-admin/src/components/AdminAdd/AdminAdd.tsx
=> refactor:머지실수수정

src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.tsx, src/front-end/timepay-front/src/pages/MyPage/My.css, src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx, src/front-end/timepay-front/src/utils/paths.ts
- 마이페이지 , 활동기록 화면에서 링크나 스타일 수정함
=> 빌드 전 세부사항 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/domain/organization/Organization.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/user/User.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/dto/AdminDealBoardDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java, src/back-end/timepay/src/main/resources/application.yml
=> Resolve Lazy / Eager Loading Issue

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/user/ApiController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/user/response/GetResponseDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/board/BoardRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/comment/CommentRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoard/DealBoard.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoardComment/DealBoardComment.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealRegister/DealRegister.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/freeBoard/FreeBoard.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/freeBoard/FreeBoardRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/freeBoardComment/FreeBoardComment.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/freeRegister/FreeRegister.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/user/User.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/dto/AdminDealBoardDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/dto/DealBoardCommentDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/dto/FreeBoardCommentDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java, src/back-end/timepay/src/main/resources/application.yml
=> Feat matching

src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java
=> Fix: 배포중인 서버 IP에 맞게 리다이렉션 URL 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/user/KakaoLoginController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/user/model/AuthenticationResponse.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java
=> Fix: 배포중인 서버 IP에 맞게 리다이렉션 URL 수정 및 return 값 수정

src/front-end/timepay-front/src/components/qna/QnaList.style.tsx, src/front-end/timepay-front/src/pages/JoinPage/JoinPage.tsx, src/front-end/timepay-front/src/pages/LoginPage/Authorization_kakao.tsx
=> [사용자] 회원가입 화면 CSS 수정

src/front-end/timepay-front/src/pages/RegisterPage/RegisterFreePage.tsx, src/front-end/timepay-front/src/pages/RegisterPage/RegisterRequestPage.tsx, src/front-end/timepay-front/src/pages/RegisterPage/RegisterServePage.tsx
- 게시글 등록 버튼 비활성화 조건 설정했습니다.
- 기존 코드가 내용 입력을 안 해도 게시글 등록이 되더라구요,,,!
- 승인 부탁드려요~
=> [사용자] 게시글 등록 버튼 비활성화 조건 설정

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/user/KakaoLoginController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/service/AutoMatchingService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java
=> Fix: 프론트 로컬 테스트용으로 수정, 배포할땐 배포용으로 수정 필요함 & 자동 매칭 서비스 껍데기만 생성

src/front-end/timepay-front/src/pages/LoginPage/Authorization_kakao.tsx
=> 사용자 카카오 리다이렉트 URL 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/config/WebConfig.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java
=> Fix: 배포된 프론트 서버의 CORS 허용, redirect 설정

src/front-end/timepay-front/src/pages/JoinPage/JoinPage.tsx
=> 회원가입 화면 지역 셀렉박스 width 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/config/UserSecurityConfig.java, src/back-end/timepay/src/main/resources/application.yml
=> Fix: api/users에 기관 회원도 접근 가능하게 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/config/UserSecurityConfig.java, src/back-end/timepay/src/main/java/com/capstone/timepay/config/WebConfig.java
=> Fix: CORS 문제 해결

src/front-end/timepay-admin/package.json, src/front-end/timepay-admin/src/api/request.ts, src/front-end/timepay-front/package.json, src/front-end/timepay-front/src/api/request.ts, src/front-end/timepay-front/src/pages/JoinPage/JoinPage.tsx, src/front-end/timepay-front/src/pages/MyEditPage/MyEditPage.tsx, src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx
- 프록시 서버를 삭제하고 request baseurl 설정함
-
=> feat: 프록시 서버 삭제

src/front-end/timepay-front/src/pages/JoinPage/JoinPage.tsx, src/front-end/timepay-front/src/pages/MyPage/My.css
=> api 및 일부 디자인 수정

src/front-end/timepay-front/src/pages/MyEditPage/MyEditPage.tsx
=> 이미지 기본값 수정

src/front-end/timepay-admin/src/api/interfaces/IAdmin.ts, src/front-end/timepay-admin/src/components/BaseLayout/BaseLayout.tsx, src/front-end/timepay-admin/src/pages/Login/LoginPage.tsx
비밀번호 오류시에 로그인 화면 안넘어가게 수정
첫로그인 여부 판별하여 비밀번호 변경 페이지 진입 여부 수정
=> [관리자] 비밀번호 오류 및 첫로그인 검증 추가

src/front-end/timepay-front/src/App.tsx, src/front-end/timepay-front/src/api/interfaces/IVolunteer.ts, src/front-end/timepay-front/src/api/urls.ts, src/front-end/timepay-front/src/pages/MyVolunteerPage/MyVolunteerPage.styles.tsx, src/front-end/timepay-front/src/pages/MyVolunteerPage/MyVolunteerPage.tsx, src/front-end/timepay-front/src/pages/MyVolunteerPage/index.ts, src/front-end/timepay-front/src/pages/index.ts, src/front-end/timepay-front/src/utils/paths.ts
- 봉사활동 기록 페이지 화면 추가
- [피그마 링크](https://www.figma.com/file/VgaJP6q5Fygk1v46pwOoqR/TIMEPAY?type=design&node-id=1322-285&t=9gj4FkxvoE3GSpTg-4)
- [기획서 링크](https://docs.google.com/presentation/d/1PVlaLM_ic0tgSZNG3l5Dyc9bYUtFTpUXC7Q0Gkc9rdo/edit#slide=id.g230a43720be_0_147)
- api 추후 연결 예정
=> [사용자] 내 봉사활동 기록 페이지 UI 개발

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/user/CheckController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java, src/back-end/timepay/src/main/resources/application.yml
배포된 환경에서는 한글 인코딩이 깨지는 문제 발견, 서버 설정을 통해 해결 시도
만약 해결되지 않는다면 아래 코드의 필터를 추가하여 시도해볼 예정
`@Bean
public CharacterEncodingFilter characterEncodingFilter() {
CharacterEncodingFilter characterEncodingFilter = new 
CharacterEncodingFilter();
characterEncodingFilter.setEncoding("UTF-8");
characterEncodingFilter.setForceEncoding(true);
return characterEncodingFilter;
}`
=> Fix: delete method 리팩터링, 닉네임 중복 검사 API POST -> GET 수정, 한글 깨짐 설정

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/board/DealBoardCommentController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/board/DealBoardController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/timetable/TimeTableController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoard/DealBoardRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoardComment/DealBoardCommentRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/timetable/TimeStamp.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/timetable/TimeStampRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/timetable/TimeTable.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/timetable/TimeTableRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/service/DealBoardCommentService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/service/DealBoardService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/timetable/TimeTableService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/timetable/dto/TimeStampDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/timetable/dto/TimeTableDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java
게시판에 이미지 들어가지 않으면 415 에러 걸리는 버그 수정
게시판값이 깨지거나 들어가지 않는 현상 수정
매칭 목록 확인후 매칭까지 진행할 수 있도록 구현
타임테이블 엔티티 추가됨(다시 기획해야함)
=> Backend 게시판 merge

src/front-end/timepay-front/src/App.tsx, src/front-end/timepay-front/src/api/interfaces/IVolunteer.ts, src/front-end/timepay-front/src/pages/VolunteerCertificationPaymentPage/VolunteerCertificationPaymentPage.styles.tsx, src/front-end/timepay-front/src/pages/VolunteerCertificationPaymentPage/VolunteerCertificationPaymentPage.tsx, src/front-end/timepay-front/src/pages/VolunteerCertificationPaymentPage/index.ts, src/front-end/timepay-front/src/pages/index.ts, src/front-end/timepay-front/src/utils/device.ts, src/front-end/timepay-front/src/utils/paths.ts
- 인증서 지급 화면 UI 추가
- 사용자 편의를 위해 PC 화면용 추가
- [피그마 링크](https://www.figma.com/file/VgaJP6q5Fygk1v46pwOoqR/TIMEPAY?type=design&node-id=1314-225&t=DA0eAGhNmyFuyh0u-4)
[기획서 링크](https://docs.google.com/presentation/d/1PVlaLM_ic0tgSZNG3l5Dyc9bYUtFTpUXC7Q0Gkc9rdo/edit#slide=id.g230a43720be_0_112)
- 추후 api 연결
=> [사용자] 인증서 지급 화면 UI 추가

src/front-end/timepay-admin/src/api/hooks/report.ts, src/front-end/timepay-admin/src/api/interfaces/IReport.ts, src/front-end/timepay-admin/src/api/urls.ts, src/front-end/timepay-admin/src/components/ReportDetailModal/ReportDetailModal.tsx, src/front-end/timepay-admin/src/components/ReportSearchForm/ReportSearchForm.styles.tsx, src/front-end/timepay-admin/src/components/ReportSearchForm/ReportSearchForm.tsx, src/front-end/timepay-admin/src/components/ReportTable/ReportTable.tsx, src/front-end/timepay-admin/src/interfaces/ReportItem.ts, src/front-end/timepay-admin/src/pages/ReportManagement/ReportManagementPage.tsx, src/front-end/timepay-admin/src/states/reportSearchState.ts
- 신고 조회
- 회원 제재처리
- 신고 검색 기능 현재 파라미터로 검색중이라 에러뜨는데 백엔드분이랑 조율해서 고치겠습니다 . . .
=> [관리자] 신고관리 기능 연결

src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/CommentManageService.java
=> Fix : 오타 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/domain/user/UserRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/CommentManageService.java
=> Fix : 댓글 검색 이름 포함 수정

src/front-end/timepay-admin/src/api/hooks/comment.ts, src/front-end/timepay-admin/src/api/interfaces/IComment.ts, src/front-end/timepay-admin/src/components/CommentSearchForm/CommentSearchForm.tsx, src/front-end/timepay-admin/src/components/CommentTable/CommentTable.tsx, src/front-end/timepay-admin/src/states/commentSearchState.ts, src/front-end/timepay-admin/src/utils/pagination.ts
- 댓글 검색 api 안되던 거 수정
- 리턴 값 바뀐 거 적용
- 페이지네이션 defaultCurrent -> current, defaultPageSize -> pageSize 수정
=> [관리자] 댓글 관리 화면 수정

src/front-end/timepay-front/src/api/hooks/inquiry.ts, src/front-end/timepay-front/src/api/hooks/register.ts, src/front-end/timepay-front/src/api/interfaces/IPost.ts, src/front-end/timepay-front/src/api/interfaces/IQna.ts, src/front-end/timepay-front/src/api/request.ts, src/front-end/timepay-front/src/api/urls.ts, src/front-end/timepay-front/src/components/post/PostButton.tsx, src/front-end/timepay-front/src/components/qna/QnaList.tsx, src/front-end/timepay-front/src/pages/PostPage/PostPage.style.tsx, src/front-end/timepay-front/src/pages/QnaPage/QnaListPage.tsx, src/front-end/timepay-front/src/pages/QnaPage/QnaRegisterPage.tsx, src/front-end/timepay-front/src/pages/RegisterPage/RegisterFreePage.style.tsx, src/front-end/timepay-front/src/pages/RegisterPage/RegisterRequestPage.tsx, src/front-end/timepay-front/src/pages/RegisterPage/RegisterServePage.tsx
api 연결 성공했습니다. UI랑 더 자세한 내용은 앞으로 더 수정할게요.
=> [사용자] 도움받기 게시글 작성 api 연결

src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoardComment/DealBoardCommentRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/user/UserRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/CommentManageService.java
=> Fix : 댓글 검색 시 조회되지 않으면 발생하는 에러 해결

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/board/DealBoardCommentController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/user/response/GetResponseDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoard/DealBoard.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoard/DealBoardRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/service/DealRegisterService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java
=> Fix: (타)유저 프로필 조회 댓글 조회 수정, 자동 매칭 개발 완료

src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java
=> Fix: 카카로 로그인 호스트 변경

src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/ReportManageService.java
=> Fix : 관리자 신고 관리 포함 검색으로 변경

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/ReportManageController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/ReportManageService.java
=> Fix : 관리자 신고 검색 값 없을 때 빈 페이지 나오도록 수정

src/front-end/timepay-admin/src/api/hooks/report.ts, src/front-end/timepay-admin/src/api/interfaces/IReport.ts, src/front-end/timepay-admin/src/components/ReportTable/ReportTable.tsx, src/front-end/timepay-admin/src/states/reportSearchState.ts, src/front-end/timepay-admin/yarn.lock
=> Fix: 신고관리 오류 수정

src/front-end/timepay-front/src/api/hooks/category.ts, src/front-end/timepay-front/src/api/interfaces/ICategory.ts, src/front-end/timepay-front/src/api/urls.ts, src/front-end/timepay-front/src/assets/images/icons/timepay-character-logo.svg, src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.styles.tsx, src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.tsx, src/front-end/timepay-front/src/pages/AgencySignInPage/AgencySignInPage.tsx, src/front-end/timepay-front/src/pages/HomePage/HomePage.styles.tsx, src/front-end/timepay-front/src/pages/HomePage/HomePage.tsx, src/front-end/timepay-front/src/styles/constants/colors.ts, src/front-end/timepay-front/src/styles/constants/tabStyle.ts
- 홈화면 Ui 수정함
- 카테고리 get api 사용
- 베이스레이아웃 일부 수정
- 활동 기록 화면 배경색 삭제
=> [사용자] 홈화면 ui 수정, 카테고리 api 연결

src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.tsx, src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.styles.tsx, src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.tsx, src/front-end/timepay-front/src/styles/constants/customTheme.ts
- 검색 헤더 옵션 축소 및 디자인 수정
- 게시글 컴포넌트 더보기 버튼 삭제
- 커스텀 테마 컬러 main 1 컬러로 변경
=> [사용자] 검색 화면 ui 수정

src/front-end/timepay-front/src/pages/LoginPage/LoginPage.tsx
- 자동로그인 불가하도록 토큰 있어도 로그인 화면으로 가도록 수정
=> chore: 자동 로그인 불가 처리

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/user/UserMypageController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/user/response/GetResponseDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoard/DealBoardRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/service/DealRegisterService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java
=> (타)유저 프로필 API 분리

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/NotificationController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/firebase/FirebaseService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/firebase/dto/FCMDto.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/NotificationService.java
- Query param을 통해 요청하던 공지사항 데이터를 Request Part 요청으로 변경하였습니다.
- 아래와 같이 FORM DATA를 구성해야 하며 "notification" key 값에는 아래 데이터를,
```json
{
"content": "string",
"isNotice": true,
"state": "string",
"title": "string"
}
```
"image" key 값에는 이미지 데이터를 넣으면 됩니다. (필수 아님)
=> Fix notifcation issue

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/board/BoardSearchController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/board/DealBoardController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/board/DealBoardSearchController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/board/InquiryController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/board/DealBoardSearch.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoard/DealBoard.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoard/DealBoardRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoard/DealBoardSearch.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/inquiry/InquiryRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/dto/DealBoardDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/dto/InquiryDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/service/DealBoardService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/service/DealRegisterService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/service/InquiryService.java
게시글 일부 오류사항 수정
게시글 검색기능 추가
문의게시판 에러 및, Principle 적용, 페이지네이션 적용, 내가 쓴 문의게시판 조회 추가
레지스터가 계속 null이 되는 현상 에러 수정
=> Backend 0509

src/front-end/timepay-front/src/App.tsx, src/front-end/timepay-front/src/pages/CategorySelectPage/CategorySelectPage.styles.tsx, src/front-end/timepay-front/src/pages/CategorySelectPage/CategorySelectPage.tsx, src/front-end/timepay-front/src/pages/JoinPage/JoinPage.tsx, src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx, src/front-end/timepay-front/src/states/categorySelect.ts, src/front-end/timepay-front/src/utils/paths.ts
- 관심분야 알림 화면 UI 구현
- 마이페이지 수정해서 관심분야 알림 화면과 연결
- 회원가입 후 관심분야 알림 화면과 연결
=> [사용자] 관심분야 알림 화면 UI

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/user/UserMypageController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java
=> Fix: 유저 프로필 조회 API 매칭 및 수정

src/front-end/timepay-admin/src/utils/token.ts
- 하루 단위로 사용하던 토큰 백엔드에 맞춰서 10시간으로 수정했습니다.
=> [관리자] 토큰 발급 단위 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/config/WebConfig.java
=> Fix: 프론트 3001번 호스트 CORS 에러 해결

src/front-end/timepay-admin/src/pages/Login/LoginPage.tsx, src/front-end/timepay-admin/src/utils/token.ts
=> refactor: 토큰 발급 부분 코드 리팩토링

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/user/UserMypageController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java
=> Feat: 이미지가 null일 경우, DB에는 빈 문자열로 저장 / 유저 토큰도 동일(추후 수정 예정)

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/response/inquiry/InquiryResponse.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/InquiryManagerService.java
=> Fix : 관리자 문의 조회 content 추가

src/front-end/timepay-admin/src/api/hooks/notification.ts, src/front-end/timepay-admin/src/api/request.ts, src/front-end/timepay-admin/src/api/urls.ts, src/front-end/timepay-admin/src/components/PushAddModal/PushAddModal.tsx
- POST api/notifications 호출 시 form data 로 보내도록 수정
=> [관리자] 공지 작성 form data로 보내도록 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java
=> 배포 호스트 변경 및 User 테이블에 최대한 NULL 값 없도록 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/AdminBoardController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoard/DealBoardSearch.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/AdminBoardService.java
=> feat: 관리자 게시글 검색 기능 추가

src/back-end/timepay/src/main/java/com/capstone/timepay/domain/user/User.java
=> Fix: User Entity에서 OneToMany 관계에 (cascade = CascadeType.REMOVE) 옵션 추가

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/board/DealBoardSearchController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/user/UserMypageController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/board/DealBoardSearch.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoard/DealBoardSearch.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoardComment/DealBoardCommentRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoardComment/DealBoardCommentSearch.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/dto/DealBoardDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/dto/InquiryDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/service/DealBoardService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/service/InquiryService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java
세윤님 Inquiry 수정사항 반영
준원님 수정사항 반영
게시글 오류사항 반영
검색안되는 에러 수정
=> Backend 0514

src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java
=> Fix: User Entity가 삭제될 때, userProfile 참조 관련 문제 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/domain/user/User.java
=> Feat deputy

src/front-end/timepay-front/src/pages/MyEditPage/MyEditPage.tsx, src/front-end/timepay-front/src/pages/MyPage/My.css
=> [사용자] 마이페이지 수정 화면 - 닉네임 중복 관련 수정

src/front-end/timepay-front/src/pages/MyPage/My.css
=> 마이페이지 margin 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/domain/user/User.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java
=> Feat: 최초 로그인시, 회원가입을 하지 않더라도 user_profile 객체를 user 객체에 저장하도록 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java
=> Fix: 배포 호스트로 변경(신경쓰기..)

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/AdminBoardController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/response/board/DealBoardResponse.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoard/DealBoardSearch.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/AdminBoardService.java
=> fix: 어드민 게시글 검색 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/InquiryManageController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/inquiry/Inquiry.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/inquiry/InquiryRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/InquiryManagerService.java
=> Fix : 관리자 문의 관리 검색 기능 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/user/ApiController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/user/request/BookmarkDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/user/User.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java
=> Feat: 회원가입시 관심분야 설정 API 개발

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/user/ApiController.java
=> Fix: 관심분야 설정 response에 HttpStatus.OK 추가

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/AdminBoardController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/board/DealBoardSearchController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoard/DealBoard.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/dto/DealBoardDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/service/DealBoardService.java
게시글 유저정보 검색화면에 들어가도록 추가
페이지네이션 오류 및 이름 표기 수정
=> 0514 backend

src/back-end/timepay/src/main/java/com/capstone/timepay/TimepayApplication.java
=> chore: 서버 시간 Asia/Seoul로 변경

src/front-end/timepay-admin/src/pages/PasswordEdit/PasswordEditPage.tsx
- 비밀번호 변경시 현재 비밀번호틀려도 넘어가지는 오류 수정
=> fix: 비밀번호 변경 오류 수정

src/front-end/timepay-admin/src/api/interfaces/IAdmin.ts, src/front-end/timepay-admin/src/components/AdminAdd/AdminAdd.tsx, src/front-end/timepay-admin/src/components/AdminMainTable/AdminMainTable.tsx
=> chore: 관리자 컬럼 수정

src/front-end/timepay-admin/src/pages/UserManagement/UserManagementPage.tsx
=> 관리자 회원관리 error 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/user/UserMypageController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoard/DealBoard.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealBoardComment/DealBoardCommentSearch.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/user/User.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java, src/back-end/timepay/src/main/resources/application.yml
=> Feat: 타 유저 프로필 조회 게시글, 댓글 API 분리, 내 활동기록 댓글 쿼리 수정

src/front-end/timepay-front/src/api/hooks/user.ts, src/front-end/timepay-front/src/api/interfaces/IComment.ts, src/front-end/timepay-front/src/api/interfaces/ICommon.ts, src/front-end/timepay-front/src/api/interfaces/IUser.ts, src/front-end/timepay-front/src/api/urls.ts, src/front-end/timepay-front/src/components/ActivityCommentCard/ActivityCommentCard.styles.tsx, src/front-end/timepay-front/src/components/ActivityCommentCard/ActivityCommentCard.tsx, src/front-end/timepay-front/src/components/ActivityPostCard/ActivityPostCard.styles.tsx, src/front-end/timepay-front/src/components/ActivityPostCard/ActivityPostCard.tsx, src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.styles.tsx, src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.tsx
=> [사용자] 활동 기록 화면 기능 연결

src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java
=> Fix: 백 로컬 호스트로 설정되어 있었던 카카오톡 로그인을 배포 서버로 변경

src/back-end/timepay/src/main/java/com/capstone/timepay/TimepayApplication.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/response/board/DealBoardResponse.java, src/back-end/timepay/src/main/resources/application.yml
=> Admin Board Search bug fix

src/front-end/timepay-front/src/api/hooks/user.ts, src/front-end/timepay-front/src/api/interfaces/IComment.ts, src/front-end/timepay-front/src/api/interfaces/IUser.ts, src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.tsx
=> fix: 활동기록 타입에러 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/board/DealBoardCommentController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/service/DealBoardCommentService.java
DealBoardComment Controller 와 Service의 코드 수정
=> fix: 게시판 댓글 삭제가 안되는 현상 수정

src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.styles.tsx, src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.tsx, src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.styles.tsx
=> 홈화면 검색화면에 알림함 추가

src/front-end/timepay-front/src/pages/MyEditPage/MyEditPage.tsx, src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx
=> [사용자] 개인 사용자 마이페이지, 내 정보 수정 화면 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java
=> Fix: 기관 회원 조회 안되던 버그 수정

src/front-end/timepay-front/src/api/hooks/push.ts, src/front-end/timepay-front/src/api/interfaces/IPush.ts, src/front-end/timepay-front/src/api/request.ts, src/front-end/timepay-front/src/components/PushCollapse/PushCollapse.tsx, src/front-end/timepay-front/src/pages/PushNotificationPage/PushNotificationPage.tsx
- 알림함 조회하는 api 수정
- view 속성 바꾸는 api 추가 연결
=> chore: 알림함 api 연결 수정, view 속성 바꾸는 api 추가

src/front-end/timepay-front/src/App.tsx, src/front-end/timepay-front/src/api/hooks/agency.ts, src/front-end/timepay-front/src/api/hooks/user.ts, src/front-end/timepay-front/src/api/interfaces/IAgency.ts, src/front-end/timepay-front/src/api/request.ts, src/front-end/timepay-front/src/api/urls.ts, src/front-end/timepay-front/src/pages/AgencyEditPage/AgencyEdit.styles.tsx, src/front-end/timepay-front/src/pages/AgencyEditPage/AgencyEditPage.tsx, src/front-end/timepay-front/src/pages/AgencyEditPage/index.ts, src/front-end/timepay-front/src/pages/AgencySignInPage/AgencySignInPage.tsx, src/front-end/timepay-front/src/pages/MyPage/MyPage.styles.tsx, src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx, src/front-end/timepay-front/src/pages/index.ts, src/front-end/timepay-front/src/utils/paths.ts
- 기관 회원 마이페이지 화면 수정
- 기관 정보 수정 페이지 추가
=> [사용자] 기관 회원 마이페이지 조회, 정보 수정 페이지 추가 및 기능 연결

src/front-end/timepay-front/src/api/hooks/user.ts, src/front-end/timepay-front/src/api/interfaces/IUser.ts, src/front-end/timepay-front/src/pages/LoginPage/Login.styles.ts, src/front-end/timepay-front/src/pages/LoginPage/LoginPage.tsx
- 로그인 화면 스타일 수정, 기관 회원으로 가는 링크 버튼 추가
=> [사용자] 로그인 화면 스타일 수정, 기관 회원으로 가는 링크 버튼 추가

src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/dto/OrgUserInfoDTO.java
=> Fix: 기관 회원 조회 DTO 형식을 일반 회원 조회 DTO과 동일하게 수정

src/front-end/timepay-front/src/api/hooks/board.ts, src/front-end/timepay-front/src/api/hooks/comment.ts, src/front-end/timepay-front/src/api/interfaces/IComment.ts, src/front-end/timepay-front/src/api/interfaces/IPost.ts, src/front-end/timepay-front/src/api/urls.ts, src/front-end/timepay-front/src/components/post/Item.style.tsx, src/front-end/timepay-front/src/components/post/Item.tsx, src/front-end/timepay-front/src/pages/PostPage/PostPage.style.tsx, src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx, src/front-end/timepay-front/src/pages/RegisterPage/RegisterRequestPage.tsx
- 게시글 등록 시 메시지 수정
- 게시글 등록 시 카테고리 값 post되게 수정
- 게시글 작성자 유무에 따른 수정&삭제 버튼 / 신고하기 버튼 각각 보이게 -> 이거 user 값이 undefined 돼서 현재는 안 보이는데 어제는 실행되는 거 확인했어요. db 타입 수정되면 다시 테스트하고 올릴게요
- 댓글 이미지 사이즈 고정
- 댓글 조회 api 연결. 댓글 없을 때는 댓글 없다는 문구 보이게
=> 게시글 조회 화면 댓글 조회 api 연결

src/front-end/timepay-front/src/api/hooks/board.ts, src/front-end/timepay-front/src/api/interfaces/IPost.ts, src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.tsx, src/front-end/timepay-front/src/components/post/PostButton.tsx, src/front-end/timepay-front/src/pages/PostPage/PostPage.style.tsx, src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx
- 기존의 simplecard의 state를 가져오는 것에서 /api/deal-boards/{id} api를 get해서 게시글을 조회하게 변경했습니다.
=> [사용자] 게시글 조회 api 연결

src/front-end/timepay-front/src/components/MainFooter/MainFooter.tsx, src/front-end/timepay-front/src/components/PostStatusTag/PostStatusTag.styles.tsx, src/front-end/timepay-front/src/components/PostStatusTag/PostStatusTag.tsx, src/front-end/timepay-front/src/components/PostTypeTag/PostTypeTag.styles.tsx, src/front-end/timepay-front/src/components/PostTypeTag/PostTypeTag.tsx, src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.styles.tsx, src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.tsx, src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.styles.tsx, src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.tsx, src/front-end/timepay-front/src/index.css, src/front-end/timepay-front/src/pages/SearchPage/SearchPage.styles.tsx, src/front-end/timepay-front/src/pages/SearchPage/SearchPage.tsx
=> [사용자] 검색화면 큰 글씨 버전 추가

src/front-end/timepay-front/src/components/ActivityCommentCard/ActivityCommentCard.styles.tsx, src/front-end/timepay-front/src/components/ActivityCommentCard/ActivityCommentCard.tsx, src/front-end/timepay-front/src/components/ActivityPostCard/ActivityPostCard.styles.tsx, src/front-end/timepay-front/src/components/ActivityPostCard/ActivityPostCard.tsx, src/front-end/timepay-front/src/components/AnotherUserProfileDrawer/AnotherUserProfileDrawer.tsx, src/front-end/timepay-front/src/index.css, src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.styles.tsx, src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.tsx, src/front-end/timepay-front/src/pages/PushNotificationPage/PushNotificationPage.tsx, src/front-end/timepay-front/src/styles/constants/tabStyle.ts
- 활동기록 큰 글씨 버전 추가, 게시글로 링크 추가
- 활동기록 탭 스타일 바꾸면서 다른 화면도 탭은 큰 글씨 버전 추가됨
=> design: 활동기록 큰 글씨 버전 추가, 게시글로 링크 추가

src/front-end/timepay-front/src/App.tsx, src/front-end/timepay-front/src/api/hooks/user.ts, src/front-end/timepay-front/src/api/interfaces/IAgency.ts, src/front-end/timepay-front/src/api/interfaces/IUser.ts, src/front-end/timepay-front/src/components/InstantActivityQRModal/InstantActivityQRModal.styles.tsx, src/front-end/timepay-front/src/components/InstantActivityQRModal/InstantActivityQRModal.tsx, src/front-end/timepay-front/src/components/InstantActivityQRModal/index.ts, src/front-end/timepay-front/src/components/MainFooter/MainFooter.tsx, src/front-end/timepay-front/src/index.css, src/front-end/timepay-front/src/pages/AgencyEditPage/AgencyEditPage.tsx, src/front-end/timepay-front/src/pages/InstantActivityPage/InstantActivityPage.styles.tsx, src/front-end/timepay-front/src/pages/InstantActivityPage/InstantActivityPage.tsx, src/front-end/timepay-front/src/pages/InstantActivityPage/index.ts, src/front-end/timepay-front/src/pages/MyPage/MyPage.styles.tsx, src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx, src/front-end/timepay-front/src/pages/index.ts, src/front-end/timepay-front/src/utils/paths.ts
- 바로 도움 요청 QR 모달 추가
- 바로 도움 요청 일지 작성 화면 추가
- 큰 글씨 버전도 추가함
=> [사용자] 바로도움요청 화면 추가

src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/KakaoLoginService.java
=> Fix: 백 로컬 호스트를 배포 서버 로컬 호스트로 변경

src/front-end/timepay-front/src/pages/MyPage/MyPage.styles.tsx
=> [사용자] 마이페이지 닉네임 겹침 수정

src/app/flutter/android/app/build.gradle, src/app/flutter/lib/main.dart, src/app/flutter/pubspec.lock, src/app/flutter/pubspec.yaml, src/front-end/timepay-front/src/pages/JoinPage/JoinPage.tsx, src/front-end/timepay-front/src/utils/device.ts, src/front-end/timepay-front/src/utils/global.d.ts
- 웹뷰 패키지 다른 거로 씀
-  앱 코드에 콜백 추가 및 회원가입 시 앱에서 받아온 디바이스 토큰 보내기
=> [사용자] 앱 코드에 콜백 추가 및 회원가입 시 앱에서 받아온 디바이스 토큰 보내기 

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/agent/response/AgentRegisterResponse.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/agent/Agent.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/agent/AgentRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/user/User.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/agent/AgentService.java, src/back-end/timepay/src/main/resources/application.yml
=> Feat: 대리인 등록 기능 개발

src/app/flutter/lib/main.dart, src/front-end/timepay-front/src/pages/JoinPage/JoinPage.tsx
=> chore: 앱 오타 수정 및 콘솔 추가

src/front-end/timepay-front/src/pages/JoinPage/JoinPage.tsx, src/front-end/timepay-front/src/utils/device.ts
=> chore: 회원가입 페이지 텍스트 수정 및 deviceToken 조건문 추가

src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx
- fix: 개인 회원 탈퇴 후 기관 회원으로 가는 오류 수정
=> fix: 개인 회원 탈퇴 후 기관 회원으로 가는 오류 수정

src/front-end/timepay-front/src/api/hooks/instantMatching.ts, src/front-end/timepay-front/src/api/interfaces/IInstantMatching.ts, src/front-end/timepay-front/src/api/urls.ts, src/front-end/timepay-front/src/pages/InstantActivityPage/InstantActivityPage.tsx
- 일지 작성 2번째 스텝 활동 시작 시간, 횔동 끝 시간을 사용자 자유입력에서 활동시작시간 현재시간으로 고정 + 활동할 시간 단위 입력으로 수정함
-  바로도움요청 일지 작성 api 연결
=> feat: 바로도움요청 일지 작성 api 연결

src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.tsx, src/front-end/timepay-front/src/components/MainFooter/MainFooter.tsx, src/front-end/timepay-front/src/pages/LoginPage/kakaoRedirectHandler.tsx, src/front-end/timepay-front/src/states/uiState.ts
- 게시글 작성 버튼은 홈화면이랑 검색화면에만 보이도록 수정
- 로그인 후 이전 페이지 이동 기능 추가
=> [사용자] 베이스 레이아웃 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java
=> Feat: 작성일 기준으로 내림차순 정렬 기능 추가

src/app/flutter/android/app/src/main/AndroidManifest.xml
- AndroidManifest 수정함
- 
https://github.com/kookmin-sw/capstone-2023-09/assets/54922639/1ddc1d6a-7aa0-4a66-bf66-8c19a2bc27bf
=> feat: 안드로이드 카메라, 저장소 접근

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/response/notification/NotificationInfoResponse.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/user/UserMypageController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/user/request/DeviceTokenDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java
=> fix: notification isViewed 에러 해결, device token update api 구현

src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/NotificationService.java
=> fix: transactional annotation 추가

src/front-end/timepay-front/src/App.tsx, src/front-end/timepay-front/src/api/interfaces/IApplicant.ts, src/front-end/timepay-front/src/components/AgentModal copy/index.ts, src/front-end/timepay-front/src/components/AgentModal/AgentModal.style.tsx, src/front-end/timepay-front/src/components/AgentModal/AgentModal.tsx, src/front-end/timepay-front/src/components/AgentModal/index.ts, src/front-end/timepay-front/src/components/ApplicantModal/ApplicantModal.style.tsx, src/front-end/timepay-front/src/components/ApplicantModal/ApplicantModal.tsx, src/front-end/timepay-front/src/components/ApplicantModal/index.ts, src/front-end/timepay-front/src/components/ApplicantReceivedModal/ApplicantReceivedModal.tsx, src/front-end/timepay-front/src/components/ApplicantReceivedModal/ApplicantReceivedModalstyle.tsx, src/front-end/timepay-front/src/components/ApplicantReceivedModal/index.ts, src/front-end/timepay-front/src/index.css, src/front-end/timepay-front/src/pages/AgentPage/AgentPage.style.tsx, src/front-end/timepay-front/src/pages/AgentPage/AgentPage.tsx, src/front-end/timepay-front/src/pages/AgentPage/index.ts, src/front-end/timepay-front/src/pages/ApplicantPage/ApplicantPage.style.tsx, src/front-end/timepay-front/src/pages/ApplicantPage/ApplicantPage.tsx, src/front-end/timepay-front/src/pages/ApplicantPage/index.ts, src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx, src/front-end/timepay-front/src/pages/index.ts, src/front-end/timepay-front/src/utils/paths.ts
=> [사용자]대리인 UI추가

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/agent/AgentController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/agent/request/AgentApplyRequest.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/agent/AgentService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/agent/AgentUserService.java
=> Fix: 대리인 등록 오류 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/service/agent/AgentService.java
=> Feat: 대리인 -> 신청인 수락 및 거절 기능 개발

src/front-end/timepay-front/src/components/InstantActivityQRModal/InstantActivityQRModal.tsx, src/front-end/timepay-front/src/components/MainFooter/MainFooter.tsx, src/front-end/timepay-front/src/pages/InstantActivityPage/InstantActivityPage.tsx
=> [사용자] 바로활동 -자신과 활동 못하게 수정, 활동 내역 없을때 작성 안되게 수정, 가이드 문구 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/service/agent/AgentService.java
=> Fix: 대리인 -> 신청인 조회에서 신청인이 없을 경우 예외처리

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/agent/response/AgentUserInfoResponse.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/agent/AgentUserService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/dto/OrgUserInfoDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/user/service/UserInfoService.java
=> Fix: 신청인이 대리인을 조회할 때, 승인 여부도 함께 알려주도록 수정 / 기관 회원 조회할 때 userID도 함께 주도록 설정

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/board/DonateBoardController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/dealRegister/DealRegister.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/donateBoard/DonateBoard.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/dto/DonateBoardDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/service/DonateBoardService.java
기부하기 게시글에 유저정보(id, nickname, name, imageURL, 타입) 들어가도록 수정 유저 프로필에도 기부하기 게시판이 조회되도록 수정
=> fix : 기부 게시판 페이지네이션이 최신순이 되도록 수정,

src/front-end/timepay-front/src/api/hooks/comment.ts, src/front-end/timepay-front/src/api/interfaces/IComment.ts, src/front-end/timepay-front/src/api/urls.ts, src/front-end/timepay-front/src/components/post/Item.style.tsx, src/front-end/timepay-front/src/components/post/Item.tsx, src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx
=> [사용자] 댓글 등록 api, 댓글 삭제 api 연결

src/front-end/timepay-front/src/pages/LoginPage/kakaoRedirectHandler.tsx
=> fix: 디바이스토큰 패치 로직 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/organization/request/OrgaUserSignUpRequest.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/organization/Organization.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/organization/OrganizationUserService.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/organization/dto/OrgaUserSignUpDto.java
=> Fix : 기관 회원 회원가입 수정

src/front-end/timepay-front/src/api/hooks/device.ts
=> fix:디바이스 토큰 수정 2

src/back-end/timepay/src/main/java/com/capstone/timepay/service/agent/AgentService.java
=> Fix: 승인/거부 상태만 받고 DB에 저장하지 않은 문제 해결

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/AdminOrgaManageController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/response/organization/OrganizationMain.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/organization/OrganizationRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/user/UserRepository.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/AdminOrgaManageService.java
=> Feat : 관리자 기관 회원 관리 기능 구현

src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/AdminOrgaManageService.java
=> Fix : 기관 회원 검색 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/dto/DealBoardDTO.java
=> fix: DelaBoard DTO에 Volunteer 추가

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/board/DonateBoardController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/domain/donateBoard/DonateBoard.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/dto/DonateBoardDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/service/DonateBoardService.java
=> Backend 0522

src/front-end/timepay-front/src/App.tsx, src/front-end/timepay-front/src/api/hooks/donation.ts, src/front-end/timepay-front/src/api/interfaces/IAgency.ts, src/front-end/timepay-front/src/api/interfaces/IDonation.ts, src/front-end/timepay-front/src/api/urls.ts, src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.tsx, src/front-end/timepay-front/src/pages/DonationBoardEditPage/DonationBoardEditPage.styles.tsx, src/front-end/timepay-front/src/pages/DonationBoardEditPage/DonationBoardEditPage.tsx, src/front-end/timepay-front/src/pages/DonationBoardEditPage/index.ts, src/front-end/timepay-front/src/pages/DonationBoardPage/DonationBoardPage.style.tsx, src/front-end/timepay-front/src/pages/DonationBoardPage/DonationBoardPage.tsx, src/front-end/timepay-front/src/pages/DonationBoardWritePage/DonationBoardWritePage.tsx, src/front-end/timepay-front/src/pages/index.ts
- 작성자일 경우 수정하기, 삭제하기 가능하도록 하고 api 연결함
=> [사용자] 기부하기 게시글 수정, 삭제, 작성자 여부 추가

src/front-end/timepay-front/src/api/hooks/user.ts, src/front-end/timepay-front/src/components/AnotherUserProfileDrawer/AnotherUserProfileDrawer.styles.tsx, src/front-end/timepay-front/src/components/AnotherUserProfileDrawer/AnotherUserProfileDrawer.tsx, src/front-end/timepay-front/src/pages/DonationBoardPage/DonationBoardPage.tsx
- 타유저 프로필 화면 api 연결함 (기본 정보, 게시글, 댓글)
- open이랑 userId 가 둘 다 있어야만 프로필에서 정보를 제대로 표시
- 일단 기부하기 게시글 - 작성자에만 연결했고 추후 다 추가할 예정!
=> [사용자] 타유저프로필 화면 기능 연결

src/front-end/timepay-front/src/api/hooks/board.ts, src/front-end/timepay-front/src/api/hooks/comment.ts, src/front-end/timepay-front/src/api/hooks/reports.ts, src/front-end/timepay-front/src/api/interfaces/IPost.ts, src/front-end/timepay-front/src/components/post/Item.tsx, src/front-end/timepay-front/src/pages/PostPage/PostPage.style.tsx, src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx, src/front-end/timepay-front/src/pages/RegisterPage/RegisterRequest.styles.tsx, src/front-end/timepay-front/src/pages/RegisterPage/RegisterRequestPage.tsx
- 댓글 무한 호출 에러 수정, 봉사활동 지급 게시글 등록, 자동 매칭 게시글 등록 추가
=> [사용자] 댓글 무한 호출 에러 수정, 봉사활동 지급 게시글 등록, 자동 매칭 게시글 등록 추가

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/response/board/DealBoardResponse.java
=> fix: 검색에 기관 이름이 오도록 구현

src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.tsx, src/front-end/timepay-front/src/pages/PostPage/PostPage.style.tsx, src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx, src/front-end/timepay-front/src/pages/RegisterPage/RegisterRequestPage.tsx
- 기관 작성 게시글일 때 기관명 추가, 봉사활동 게시글일 때 설명 추가
- 지원, 선정, 활동 완료가 잘 되어야 인증서 지급 화면,
=> [사용자] 기관 작성 게시글일 때 기관명 추가, 봉사활동 게시글일 때 설명 추가

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/board/DealBoardController.java
=> fix: 기관으로 글썼을때 상태 안바뀌는 에러 수정

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/board/DealBoardCommentController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/dto/AdoptedCommentDTO.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/board/service/DealBoardCommentService.java
=> feat: 선정된 댓글"들"을 선정하고 게시글 상태를 변경하도록 구현

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/AdminOrgaManageController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/response/organization/OrganizationMain.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/AdminOrgaManageService.java
=> Fix : 기관 회원 관리 페널티 정보 추가

src/front-end/timepay-front/src/api/hooks/agency.ts, src/front-end/timepay-front/src/api/hooks/user.ts, src/front-end/timepay-front/src/api/interfaces/ICommon.ts, src/front-end/timepay-front/src/api/interfaces/IVolunteer.ts, src/front-end/timepay-front/src/api/urls.ts, src/front-end/timepay-front/src/components/post/PostButton.style.tsx, src/front-end/timepay-front/src/components/post/PostButton.tsx, src/front-end/timepay-front/src/pages/MyVolunteerPage/MyVolunteerPage.tsx, src/front-end/timepay-front/src/pages/VolunteerCertificationPaymentPage/VolunteerCertificationPaymentPage.tsx
- 연결 완료, 테스트 완료
- 봉사 시간이 자꾸 0으로 들어가는 건 용훈님께 말씀드린 상태
=> [사용자] 봉사활동 인증서 지급/ 내 봉사활동 메뉴 기능 연결

src/front-end/timepay-admin/src/api/interfaces/IAgency.ts, src/front-end/timepay-admin/src/components/AgencyTable/AgencyTable.tsx, src/front-end/timepay-admin/src/components/PostTable/PostTable.tsx, src/front-end/timepay-admin/src/states/agencySearchState.ts
- 기관 관리 - 페이지네이션, 블랙리스트 여부 추가
- 게시글 관리 - 시간 포맷 수정
=> [관리자] 기관 관리, 게시글 관리 일부 수정

src/front-end/timepay-front/src/components/post/Item.tsx
=> fix: 머지 실수 수정

src/front-end/timepay-front/src/components/AnotherUserProfileDrawer/AnotherUserProfileDrawer.tsx
=> chore: 타유저 프로필 없을 때 조건 수정

src/front-end/timepay-front/src/components/post/Item.style.tsx, src/front-end/timepay-front/src/components/post/Item.tsx, src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx
- 게시글 작성자인 사람과 그렇지 않은 사람 구분 / 지원하기 선택한 사람과 아닌 사람을 구분하여 댓글 디자인을 조금씩 바꿨습니다.
=> [사용자] 댓글 작성자가 누구인지에 따른 댓글 UI 디자인

src/front-end/timepay-admin/src/components/PostTable/PostTable.tsx
=> [관리자] 게시글 관리 : endTime이 null 일 때 처리

src/front-end/timepay-front/src/components/MainHeader/MainHeader.tsx, src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.tsx, src/front-end/timepay-front/src/pages/HomePage/HomePage.tsx, src/front-end/timepay-front/src/pages/LoginPage/kakaoRedirectHandler.tsx
=> fix: 대리인 기능 종료시 제대로 종료 안되는/로그인시 대리인 기능 안풀리는 문제 해결

src/front-end/timepay-front/src/components/PushCollapse/PushCollapse.styles.tsx, src/front-end/timepay-front/src/components/PushCollapse/PushCollapse.tsx, src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.styles.tsx, src/front-end/timepay-front/src/pages/DonationBoardPage/DonationBoardPage.style.tsx, src/front-end/timepay-front/src/pages/DonationBoardPage/DonationBoardPage.tsx, src/front-end/timepay-front/src/pages/MyEditPage/MyEdit.styles.tsx, src/front-end/timepay-front/src/pages/MyEditPage/MyEditPage.tsx, src/front-end/timepay-front/src/pages/MyVolunteerPage/MyVolunteerPage.styles.tsx, src/front-end/timepay-front/src/pages/MyVolunteerPage/MyVolunteerPage.tsx
- 알림함, 기부하기, 봉사활동 기록, 내 정보 수정 화면 큰 글씨 추가함
=> [사용자] 큰 글씨 버전 추가

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/organization/response/VolunteerInfo.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/organization/OrganizationManageService.java
무슨 이유로 코드를 변경했는지
어떤 위험이나 장애가 발견되었는지
어떤 부분에 리뷰어가 집중하면 좋을지
=> Fix : Volunteer Info에 Volunteer Time 추가

src/front-end/timepay-front/src/components/post/PostButton.tsx, src/front-end/timepay-front/src/index.css, src/front-end/timepay-front/src/pages/RegisterPage/RegisterRequestPage.tsx
선정하기 모달에서 타임페이 표시
도움요청 게시글 작성 시 보유 타임페이량에 따라서 등록이 되지 않도록 처리 + 안내 모달 추가
모달 쓸 때 확인 버튼 색상 전역적으로 수정함(main1 색으로)
=> [사용자] 선정하기 모달, 도움요청 게시글 등록 시 타임페이량 안내 및 등록 불가 처리

src/front-end/timepay-front/src/pages/DonationBoardPage/DonationBoardPage.tsx, src/front-end/timepay-front/src/pages/VolunteerCertificationPaymentPage/VolunteerCertificationPaymentPage.tsx
봉사활동 인증서 화면이랑 게시글 조회 화면 자잘하게 수정함
=> [사용자] 봉사활동 인증서 지급 화면, 기부하기 화면 수정

src/front-end/timepay-front/src/api/hooks/agency.ts, src/front-end/timepay-front/src/api/interfaces/IDonation.ts, src/front-end/timepay-front/src/api/interfaces/IPost.ts, src/front-end/timepay-front/src/api/urls.ts, src/front-end/timepay-front/src/components/ActivityDonationCard/ActivityDonationCard.styles.tsx, src/front-end/timepay-front/src/components/ActivityDonationCard/ActivityDonationCard.tsx, src/front-end/timepay-front/src/components/ActivityDonationCard/index.ts, src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.tsx, src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.tsx
- 기관 활동기록 화면에 모금 현황 화면 추가 및 api 연결
- 검색 화면에서 기부하기 작성일시 안 나와서 수정 함께 함
=> [사용자] 기관 활동기록 화면에 모금 현황 화면 추가 및 api 연결

src/app/flutter/.vscode/launch.json, src/app/flutter/README.md, src/app/flutter/android/app/build.gradle, src/app/flutter/android/app/proguard-rules.pro, src/app/flutter/android/app/src/main/kotlin/com/example/flutter_application_1/MainActivity.kt, src/app/flutter/linux/CMakeLists.txt, src/app/flutter/linux/my_application.cc, src/app/flutter/macos/Runner.xcodeproj/project.pbxproj, src/app/flutter/macos/Runner.xcworkspace/contents.xcworkspacedata, src/app/flutter/pubspec.yaml, src/app/flutter/web/index.html, src/app/flutter/web/manifest.json, src/app/flutter/windows/CMakeLists.txt, src/app/flutter/windows/runner/Runner.rc, src/app/flutter/windows/runner/main.cpp
패키지 이름을 timepay로 모두 수정
로컬에서 디버깅 하고 싶을 때는 build.gradle에서 release 부분을 주석처리하고 debug 써있는 거를 주석 풀어주세요~
[apk 추출 참고](https://velog.io/@cho2kkh/Flutter-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EC%95%B1-%EB%B0%B0%ED%8F%ACAP)
직접 apk 뽑으려면 아래 사진처럼 key.jks, key.properties 추가해주세요!
=> refactor: 앱 패키지 이름 수정 및 빌드 환경 구성

src/app/flutter/android/app/src/main/AndroidManifest.xml, src/app/flutter/lib/main.dart, src/app/flutter/pubspec.lock, src/app/flutter/pubspec.yaml, src/app/flutter/windows/flutter/generated_plugin_registrant.cc, src/app/flutter/windows/flutter/generated_plugins.cmake
앱 시작시 카메라, 폴더 접근 권한을 받고 권한이 없으면 다시 앱 시작했을 떄 alert를 띄워줌
웹뷰에서 파일 provider 추가
https://github.com/kookmin-sw/capstone-2023-09/assets/54922639/a6ec3a7c-9149-47c0-bf55-170a2bbcc1d6
=> feat: 앱 시작시 카메라, 폴더 접근 권한 허용 알림 추가

src/app/flutter/lib/main.dart
=> feat: 앱 세로모드 고정, 상태바 숨김 처리

src/front-end/timepay-front/src/components/post/Item.tsx, src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx
- 게시글 조회 화면 - 지원 댓글 작성 안되는 오류 수정
- 오류 원인 : 체크박스 state를 댓글 작성 api 를 실행 성공한 후에야 댓글 정보 state에 반영시키고 있었음
- 오류 해결 : 체크박스 값을 따로 state로 분리 안하고 댓글 정보 state로 통합 관리
- 고치면서 댓글 작성 완료 시 message 도 띄우도록 추가함
=> fix: 게시글 조회 화면 - 지원 댓글 작성 안되는 오류 수정

src/front-end/timepay-front/src/components/post/Item.tsx
게시글 작성자가 올린 댓글이면 다른 사용자에게도 해당 댓글에 대한 수정 버튼이 노출되는 오류가 있어서 수정함
삭제 버튼도 동일한 오류가 있어서 함께 수정
=> fix: 댓글 수정, 삭제 버튼 노출 오류 수정

src/front-end/timepay-front/src/pages/PostPage/PostPage.style.tsx, src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx
=> chore: 게시글 조회화면 관심기능 삭제

src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/CategoryManageController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/CommentManageController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/InquiryManageController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/ReportManageController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/UserManageController.java, src/back-end/timepay/src/main/java/com/capstone/timepay/service/organization/OrganizationManageService.java
무슨 이유로 코드를 변경했는지
어떤 위험이나 장애가 발견되었는지
어떤 부분에 리뷰어가 집중하면 좋을지
=> Fix : Pagination Request Parameter 네이밍 변경

src/front-end/timepay-front/src/pages/AgencySignInPage/AgencySignInPage.styles.tsx, src/front-end/timepay-front/src/pages/AgencySignInPage/AgencySignInPage.tsx
앱 화면에서 기관 로그인 화면 진입 시 다시 개인 로그인 화면으로 갈 방법이 없어 추가함
=> design: 기관 로그인 화면에 개인 로그인 화면으로 가는 버튼 추가

src/front-end/timepay-front/src/api/hooks/register.ts, src/front-end/timepay-front/src/api/urls.ts, src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx, src/front-end/timepay-front/src/pages/RegisterPage/RegisterFreePage.style.tsx, src/front-end/timepay-front/src/pages/RegisterPage/RegisterFreePage.tsx, src/front-end/timepay-front/src/pages/RegisterPage/RegisterServePage.tsx
같이쓰기 게시글 등록 화면 UI 수정하고 api 연결했습니다.
검색조건에서 같이쓰기 카테고리 선택 시 게시글 잘 보입니당
=> [사용자] 같이쓰기 게시글 UI & api 연결

src/front-end/timepay-front/src/api/interfaces/IComment.ts, src/front-end/timepay-front/src/components/TimeTable/TimeTable.style.tsx, src/front-end/timepay-front/src/components/TimeTable/TimeTable.tsx
=> [사용자]타임테이블 유형별 보기 추가

src/front-end/timepay-front/src/pages/ApplicantPage/ApplicantPage.tsx, src/front-end/timepay-front/src/pages/LoginPage/kakaoRedirectHandler.tsx
대리인 기능 시작하고  신청자의 대리인 조회 및 신청인 관리 페이지 못들어가게 뒤로가기 제한 기능 추가했습니다
멀티토큰 없을때는 굳이 undefined로 세팅 안하게 수정했습니다
=> [사용자]대리인 기능 뒤로가기 제한 및 토큰 발급 부분 수정

src/front-end/timepay-front/src/components/TimeTable/TimeTable.style.tsx
=> fix: 폰트크기 수정

src/front-end/timepay-front/src/pages/PostPage/PostPage.style.tsx
무슨 이유로 코드를 변경했는지
어떤 위험이나 장애가 발견되었는지
어떤 부분에 리뷰어가 집중하면 좋을지
=> 게시글 조회 화면 UI 수정

src/front-end/timepay-front/src/components/ActivityPostCard/ActivityPostCard.tsx, src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.tsx
=> [사용자] 같이하기 게시글일 때 디자인 수정

src/front-end/timepay-front/src/components/ActivityPostCard/ActivityPostCard.tsx
=> chore: 활동기록 - 게시글 작성일시 포맷 수정

src/front-end/timepay-front/src/pages/JoinPage/JoinPage.tsx
무슨 이유로 코드를 변경했는지
어떤 위험이나 장애가 발견되었는지
어떤 부분에 리뷰어가 집중하면 좋을지
=> 회원가입시 메세지 알림 추가
